version: '3.8'

services:
  postgres:
    container_name: w3Postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: w3Challenge
      POSTGRES_PASSWORD: w3Challenge
      POSTGRES_DB_NAME: w3Challenge
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: w3Challenge_pgadmin #you can change this
    depends_on:
      - postgres
    ports:
      - "5053:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@w3Challenge.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

  adonis_app:
    container_name: w3ChallengeApp
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app

volumes:
  postgres_volume:
